# golangci-lint configuration for KernelSeal

run:
  timeout: 5m
  go: '1.22'
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io.Copy
      - io.WriteString

  govet:
    enable-all: true
    disable:
      - fieldalignment # too strict for our use case
      - shadow # handled separately
      - unusedwrite # false positive on struct fields used by callers

  gofmt:
    simplify: true

  goimports:
    local-prefixes: kernelseal

  misspell:
    locale: US

  gosec:
    excludes:
      - G104 # Audit errors not checked (we handle this intentionally in some places)
      - G304 # File path provided as taint input (we validate paths)
      - G115 # Integer overflow conversion (we handle PID conversion safely)

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

issues:
  exclude-dirs:
    - vendor

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - noctx

    # Exclude known issues in generated code
    - path: ".*\\.gen\\.go"
      linters:
        - all

    # Ignore shadow warnings in specific functions where it's intentional
    - linters:
        - govet
      text: "shadow"

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
