# Hadolint configuration
# https://github.com/hadolint/hadolint

ignored:
  - DL3008  # Pin versions in apt-get
  - DL3009  # Delete apt lists
  - DL3018  # Pin versions in apk

failure-threshold: error

trustedRegistries:
  - docker.io
  - gcr.io
  - ghcr.io
